### ISSUE TITLE
The duck shouldn't only make a sound when hit but also give a visual signal

### ISSUE THREAD

**Issue by NNathaneel** [Quit975/DuckyGame#54] opened 2022-05-29 07:38 UTC
It may be turn more red for a while or later we can think of a more suitable animation for that like flapping its wings.

**Comment by Quit975** [comment] 2022-05-29 08:38
Looks like a duplicate of https://github.com/Quit975/DuckyGame/issues/18 :) closing this one

**Closed by Quit975** 2022-05-29 08:38 UTC
Labels: enhancement
